### ISSUE TITLE
Add "X-Requested-With" Header

### ISSUE THREAD

**Issue by dfx17** [waytohealth/mirth_channel_exporter#3]
Hi,

When running the exporter with Mirth Connect v3.12 I get the following error

`expected element type <list> but have <HTML>`

It works perfectly fine If I downgrade Mirth Connect to v3.8.1 or v3.7.1 (only versions I've tested so far)

The Mirth community members over in Slack pointed the following in the release notes for v3.12 - https://github.com/nextgenhealthcare/connect/wiki/3.12.0---What's-New#address-csrf-for-login-and-api-pages

Can the above header be added to the next exporter release?

Thanks for all your hard work in maintaining this! and for providing a docker image :)

Cheers,
dfx

**Comment by mkopinsky** [comment]
@dfx17 can you try checking out the x-requested-with branch and seeing if that works with Mirth 3.12?

**Comment by dfx17** [comment]
confirmed working with Mirth v3.12 (via local install and docker)
